# coding: utf-8

"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

    The version of the OpenAPI document: 2.0.32
    Contact: info@fattureincloud.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fattureincloud_python_sdk.models.get_company_plan_usage_response import (
    GetCompanyPlanUsageResponse,
)


class TestGetCompanyPlanUsageResponse(unittest.TestCase):
    """GetCompanyPlanUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCompanyPlanUsageResponse:
        """Test GetCompanyPlanUsageResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetCompanyPlanUsageResponse`
        """
        model = GetCompanyPlanUsageResponse()
        if include_optional:
            return GetCompanyPlanUsageResponse(
                data = fattureincloud_python_sdk.models.company_plan_usage.CompanyPlanUsage(
                    limit = 1.337, 
                    usage = 1.337, )
            )
        else:
            return GetCompanyPlanUsageResponse(
        )
        """

    def testGetCompanyPlanUsageResponse(self):
        """Test GetCompanyPlanUsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
