"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.10
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.api.taxes_api import TaxesApi  # noqa: E501


class TestTaxesApi(unittest.TestCase):
    """TaxesApi unit test stubs"""

    def setUp(self):
        self.api = TaxesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_f24(self):
        """Test case for create_f24

        Create F24  # noqa: E501
        """
        pass

    def test_delete_f24(self):
        """Test case for delete_f24

        Delete F24  # noqa: E501
        """
        pass

    def test_delete_f24_attachment(self):
        """Test case for delete_f24_attachment

        Delete F24 Attachment  # noqa: E501
        """
        pass

    def test_get_f24(self):
        """Test case for get_f24

        Get F24  # noqa: E501
        """
        pass

    def test_list_f24(self):
        """Test case for list_f24

        List F24  # noqa: E501
        """
        pass

    def test_modify_f24(self):
        """Test case for modify_f24

        Modify F24  # noqa: E501
        """
        pass

    def test_upload_f24_attachment(self):
        """Test case for upload_f24_attachment

        Upload F24 Attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
