"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.10
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.api.archive_api import ArchiveApi  # noqa: E501


class TestArchiveApi(unittest.TestCase):
    """ArchiveApi unit test stubs"""

    def setUp(self):
        self.api = ArchiveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_archive_document(self):
        """Test case for create_archive_document

        Create Archive Document  # noqa: E501
        """
        pass

    def test_delete_archive_document(self):
        """Test case for delete_archive_document

        Delete Archive Document  # noqa: E501
        """
        pass

    def test_get_archive_document(self):
        """Test case for get_archive_document

        Get Archive Document  # noqa: E501
        """
        pass

    def test_list_archive_documents(self):
        """Test case for list_archive_documents

        List Archive Documents  # noqa: E501
        """
        pass

    def test_modify_archive_document(self):
        """Test case for modify_archive_document

        Modify Archive Document  # noqa: E501
        """
        pass

    def test_upload_archive_document_attachment(self):
        """Test case for upload_archive_document_attachment

        Upload Archive Document Attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
