"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.9
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.model.send_e_invoice_response_data import SendEInvoiceResponseData
globals()['SendEInvoiceResponseData'] = SendEInvoiceResponseData
from fattureincloud_python_sdk.model.send_e_invoice_response import SendEInvoiceResponse


class TestSendEInvoiceResponse(unittest.TestCase):
    """SendEInvoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendEInvoiceResponse(self):
        """Test SendEInvoiceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendEInvoiceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
