"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.9
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.api.cashbook_api import CashbookApi  # noqa: E501


class TestCashbookApi(unittest.TestCase):
    """CashbookApi unit test stubs"""

    def setUp(self):
        self.api = CashbookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cashbook_entry(self):
        """Test case for create_cashbook_entry

        Create Cashbook Entry  # noqa: E501
        """
        pass

    def test_delete_cashbook_entry(self):
        """Test case for delete_cashbook_entry

        Delete Cashbook Entry  # noqa: E501
        """
        pass

    def test_get_cashbook_entry(self):
        """Test case for get_cashbook_entry

        Get Cashbook Entry  # noqa: E501
        """
        pass

    def test_list_cashbook_entries(self):
        """Test case for list_cashbook_entries

        List Cashbook Entries  # noqa: E501
        """
        pass

    def test_modify_cashbook_entry(self):
        """Test case for modify_cashbook_entry

        Modify Cashbook Entry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
