# coding: utf-8

"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

    The version of the OpenAPI document: 2.0.32
    Contact: info@fattureincloud.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import json
import unittest

from fattureincloud_python_sdk.models.company_plan_usage import CompanyPlanUsage
from functions import json_serial
from functions import create_from_json


class TestCompanyPlanUsage(unittest.TestCase):
    """CompanyPlanUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyPlanUsage(self):
        """Test CompanyPlanUsage"""
        model = CompanyPlanUsage(limit=1.337, usage=1.337)
        expected_json = '{"limit": 1.337, "usage": 1.337}'
        actual_json = json.dumps(model.to_dict(), default=json_serial)
        assert actual_json == expected_json


if __name__ == "__main__":
    unittest.main()
