"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.9
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.model.default_payment_terms_type import DefaultPaymentTermsType
from fattureincloud_python_sdk.model.entity_type import EntityType
from fattureincloud_python_sdk.model.payment_method import PaymentMethod
from fattureincloud_python_sdk.model.vat_type import VatType
globals()['DefaultPaymentTermsType'] = DefaultPaymentTermsType
globals()['EntityType'] = EntityType
globals()['PaymentMethod'] = PaymentMethod
globals()['VatType'] = VatType
from fattureincloud_python_sdk.model.entity import Entity


class TestEntity(unittest.TestCase):
    """Entity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntity(self):
        """Test Entity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Entity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
