"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.9
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.model.company_info_access_info import CompanyInfoAccessInfo
from fattureincloud_python_sdk.model.company_info_plan_info import CompanyInfoPlanInfo
from fattureincloud_python_sdk.model.company_type import CompanyType
globals()['CompanyInfoAccessInfo'] = CompanyInfoAccessInfo
globals()['CompanyInfoPlanInfo'] = CompanyInfoPlanInfo
globals()['CompanyType'] = CompanyType
from fattureincloud_python_sdk.model.company_info import CompanyInfo


class TestCompanyInfo(unittest.TestCase):
    """CompanyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyInfo(self):
        """Test CompanyInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompanyInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
