"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.9
    Contact: info@fattureincloud.it
    Generated by: https://openapi-generator.tech
"""


import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.api.clients_api import ClientsApi  # noqa: E501


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self):
        self.api = ClientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_client(self):
        """Test case for create_client

        Create Client  # noqa: E501
        """
        pass

    def test_delete_client(self):
        """Test case for delete_client

        Delete Client  # noqa: E501
        """
        pass

    def test_get_client(self):
        """Test case for get_client

        Get Client  # noqa: E501
        """
        pass

    def test_list_clients(self):
        """Test case for list_clients

        List Clients  # noqa: E501
        """
        pass

    def test_modify_client(self):
        """Test case for modify_client

        Modify Client  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
