# coding: utf-8

"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  # noqa: E501

    The version of the OpenAPI document: 2.0.27
    Contact: info@fattureincloud.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fattureincloud_python_sdk
from fattureincloud_python_sdk.api.webhooks_api import WebhooksApi  # noqa: E501
from fattureincloud_python_sdk.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = (
            fattureincloud_python_sdk.api.webhooks_api.WebhooksApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_create_webhooks_subscription(self):
        """Test case for create_webhooks_subscription

        Create a Webhook Subscription  # noqa: E501
        """
        pass

    def test_delete_webhooks_subscription(self):
        """Test case for delete_webhooks_subscription

        Delete Webhooks Subscription  # noqa: E501
        """
        pass

    def test_get_webhooks_subscription(self):
        """Test case for get_webhooks_subscription

        Get Webhooks Subscription  # noqa: E501
        """
        pass

    def test_list_webhooks_subscriptions(self):
        """Test case for list_webhooks_subscriptions

        List Webhooks Subscriptions  # noqa: E501
        """
        pass

    def test_modify_webhooks_subscription(self):
        """Test case for modify_webhooks_subscription

        Modify Webhooks Subscription  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
