# coding: utf-8

"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

    The version of the OpenAPI document: 2.1.8
    Contact: info@fattureincloud.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from fattureincloud_python_sdk.models.attachment import Attachment
from fattureincloud_python_sdk.models.currency import Currency
from fattureincloud_python_sdk.models.pending_received_document_extracted_data import PendingReceivedDocumentExtractedData
from fattureincloud_python_sdk.models.pending_received_document_payments_list_item import PendingReceivedDocumentPaymentsListItem
from fattureincloud_python_sdk.models.pending_received_document_type import PendingReceivedDocumentType
from fattureincloud_python_sdk.models.received_document_type import ReceivedDocumentType
from typing import Optional, Set
from typing_extensions import Self

class PendingReceivedDocument(BaseModel):
    """
    PendingReceivedDocument
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Pending received document id")
    var_date: Optional[date] = Field(default=None, description="Pending received document date", alias="date")
    subject: Optional[StrictStr] = Field(default=None, description="Pending received document subject")
    filename: Optional[StrictStr] = Field(default=None, description="Pending received document filename")
    type: Optional[PendingReceivedDocumentType] = PendingReceivedDocumentType.AGYO
    attachment_url: Optional[StrictStr] = Field(default=None, description="[Temporary] [Read Only] Pending received document url of the attached file")
    amount_gross: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="[Read Only] Pending received document total gross amount")
    currency: Optional[Currency] = None
    document_type: Optional[ReceivedDocumentType] = ReceivedDocumentType.EXPENSE
    supplier_name: Optional[StrictStr] = Field(default=None, description="Pending received document supplier name")
    cost_center: Optional[StrictStr] = Field(default=None, description="Pending received document cost center")
    category: Optional[StrictStr] = Field(default=None, description="Pending received document category")
    other_attachments: Optional[List[Attachment]] = Field(default=None, description="Pending received document other attachments")
    emssion_date: Optional[date] = Field(default=None, description="Pending received document emission date")
    payments_list: Optional[List[PendingReceivedDocumentPaymentsListItem]] = None
    amount_net: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Pending received document total net amount")
    amount_vat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Pending received document total vat amount")
    import_error: Optional[StrictStr] = Field(default=None, description="Pending received document import error")
    extracted_data: Optional[PendingReceivedDocumentExtractedData] = None
    __properties: ClassVar[List[str]] = ["id", "date", "subject", "filename", "type", "attachment_url", "amount_gross", "currency", "document_type", "supplier_name", "cost_center", "category", "other_attachments", "emssion_date", "payments_list", "amount_net", "amount_vat", "import_error", "extracted_data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PendingReceivedDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "attachment_url",
            "amount_gross",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in other_attachments (list)
        _items = []
        if self.other_attachments:
            for _item_other_attachments in self.other_attachments:
                if _item_other_attachments:
                    _items.append(_item_other_attachments.to_dict())
            _dict['other_attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payments_list (list)
        _items = []
        if self.payments_list:
            for _item_payments_list in self.payments_list:
                if _item_payments_list:
                    _items.append(_item_payments_list.to_dict())
            _dict['payments_list'] = _items
        # override the default output from pydantic by calling `to_dict()` of extracted_data
        if self.extracted_data:
            _dict['extracted_data'] = self.extracted_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PendingReceivedDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "date": obj.get("date"),
            "subject": obj.get("subject"),
            "filename": obj.get("filename"),
            "type": obj.get("type") if obj.get("type") is not None else PendingReceivedDocumentType.AGYO,
            "attachment_url": obj.get("attachment_url"),
            "amount_gross": obj.get("amount_gross"),
            "currency": Currency.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "document_type": obj.get("document_type") if obj.get("document_type") is not None else ReceivedDocumentType.EXPENSE,
            "supplier_name": obj.get("supplier_name"),
            "cost_center": obj.get("cost_center"),
            "category": obj.get("category"),
            "other_attachments": [Attachment.from_dict(_item) for _item in obj["other_attachments"]] if obj.get("other_attachments") is not None else None,
            "emssion_date": obj.get("emssion_date"),
            "payments_list": [PendingReceivedDocumentPaymentsListItem.from_dict(_item) for _item in obj["payments_list"]] if obj.get("payments_list") is not None else None,
            "amount_net": obj.get("amount_net"),
            "amount_vat": obj.get("amount_vat"),
            "import_error": obj.get("import_error"),
            "extracted_data": PendingReceivedDocumentExtractedData.from_dict(obj["extracted_data"]) if obj.get("extracted_data") is not None else None
        })
        return _obj


