# coding: utf-8

# flake8: noqa

"""
    Fatture in Cloud API v2 - API Reference

    Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

    The version of the OpenAPI document: 2.1.7
    Contact: info@fattureincloud.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "2.1.4"

# Define package exports
__all__ = [
    "ArchiveApi",
    "CashbookApi",
    "ClientsApi",
    "CompaniesApi",
    "EmailsApi",
    "InfoApi",
    "IssuedDocumentsApi",
    "IssuedEInvoicesApi",
    "PriceListsApi",
    "ProductsApi",
    "ReceiptsApi",
    "ReceivedDocumentsApi",
    "SettingsApi",
    "SuppliersApi",
    "TaxesApi",
    "UserApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ArchiveDocument",
    "AttachmentData",
    "CashbookEntry",
    "CashbookEntryDocument",
    "CashbookEntryKind",
    "CashbookEntryType",
    "City",
    "Client",
    "ClientType",
    "Company",
    "CompanyInfo",
    "CompanyInfoAccessInfo",
    "CompanyInfoPlanInfo",
    "CompanyInfoPlanInfoFunctions",
    "CompanyInfoPlanInfoFunctionsStatus",
    "CompanyInfoPlanInfoLimits",
    "CompanyPlanUsage",
    "CompanyType",
    "ControlledCompany",
    "CreateArchiveDocumentRequest",
    "CreateArchiveDocumentResponse",
    "CreateCashbookEntryRequest",
    "CreateCashbookEntryResponse",
    "CreateClientRequest",
    "CreateClientResponse",
    "CreateF24Request",
    "CreateF24Response",
    "CreateIssuedDocumentRequest",
    "CreateIssuedDocumentResponse",
    "CreatePaymentAccountRequest",
    "CreatePaymentAccountResponse",
    "CreatePaymentMethodRequest",
    "CreatePaymentMethodResponse",
    "CreateProductRequest",
    "CreateProductResponse",
    "CreateReceiptRequest",
    "CreateReceiptResponse",
    "CreateReceivedDocumentRequest",
    "CreateReceivedDocumentResponse",
    "CreateSupplierRequest",
    "CreateSupplierResponse",
    "CreateVatTypeRequest",
    "CreateVatTypeResponse",
    "CreateWebhooksSubscriptionRequest",
    "CreateWebhooksSubscriptionResponse",
    "Currency",
    "DetailedCountry",
    "DocumentTemplate",
    "EInvoiceRejectionReason",
    "Email",
    "EmailAttachment",
    "EmailData",
    "EmailDataDefaultSenderEmail",
    "EmailRecipientStatus",
    "EmailSchedule",
    "EmailScheduleInclude",
    "EmailStatus",
    "Entity",
    "EntityClientPreCreateInfo",
    "EntityType",
    "EventType",
    "F24",
    "F24Status",
    "FattureInCloudPlanType",
    "FunctionStatus",
    "GetArchiveDocumentResponse",
    "GetBinIssuedDocumentResponse",
    "GetBinReceivedDocumentResponse",
    "GetCashbookEntryResponse",
    "GetClientResponse",
    "GetCompanyInfoResponse",
    "GetCompanyPlanUsageResponse",
    "GetEInvoiceRejectionReasonResponse",
    "GetEmailDataResponse",
    "GetEntityClientPreCreateInfoResponse",
    "GetExistingIssuedDocumentTotalsRequest",
    "GetExistingIssuedDocumentTotalsResponse",
    "GetExistingReceivedDocumentTotalsRequest",
    "GetExistingReceivedDocumentTotalsResponse",
    "GetF24Response",
    "GetIssuedDocumentPreCreateInfoResponse",
    "GetIssuedDocumentResponse",
    "GetNewIssuedDocumentTotalsRequest",
    "GetNewIssuedDocumentTotalsResponse",
    "GetNewReceivedDocumentTotalsRequest",
    "GetNewReceivedDocumentTotalsResponse",
    "GetPaymentAccountResponse",
    "GetPaymentMethodResponse",
    "GetPriceListItemsResponse",
    "GetProductResponse",
    "GetReceiptPreCreateInfoResponse",
    "GetReceiptResponse",
    "GetReceiptsMonthlyTotalsResponse",
    "GetReceivedDocumentPreCreateInfoResponse",
    "GetReceivedDocumentResponse",
    "GetSupplierResponse",
    "GetTaxProfileResponse",
    "GetUserInfoResponse",
    "GetUserInfoResponseEmailConfirmationState",
    "GetUserInfoResponseInfo",
    "GetVatTypeResponse",
    "GetWebhooksSubscriptionResponse",
    "IssuedDocument",
    "IssuedDocumentEiData",
    "IssuedDocumentExtraData",
    "IssuedDocumentItemsListItem",
    "IssuedDocumentOptions",
    "IssuedDocumentPaymentsListItem",
    "IssuedDocumentPaymentsListItemPaymentTerms",
    "IssuedDocumentPreCreateInfo",
    "IssuedDocumentPreCreateInfoDefaultValues",
    "IssuedDocumentPreCreateInfoExtraDataDefaultValues",
    "IssuedDocumentPreCreateInfoItemsDefaultValues",
    "IssuedDocumentStatus",
    "IssuedDocumentTotals",
    "IssuedDocumentType",
    "JoinIssuedDocumentsResponse",
    "Language",
    "ListArchiveCategoriesResponse",
    "ListArchiveDocumentsResponse",
    "ListArchiveDocumentsResponsePage",
    "ListBinIssuedDocuments",
    "ListBinReceivedDocuments",
    "ListCashbookEntriesResponse",
    "ListCitiesResponse",
    "ListClientsResponse",
    "ListClientsResponsePage",
    "ListCostCentersResponse",
    "ListCountriesResponse",
    "ListCurrenciesResponse",
    "ListDeliveryNotesDefaultCausalsResponse",
    "ListDetailedCountriesResponse",
    "ListEmailsResponse",
    "ListEmailsResponsePage",
    "ListF24Response",
    "ListF24ResponseAggregatedData",
    "ListF24ResponseAggregation",
    "ListF24ResponsePage",
    "ListIssuedDocumentsResponse",
    "ListIssuedDocumentsResponsePage",
    "ListLanguagesResponse",
    "ListPaymentAccountsResponse",
    "ListPaymentMethodsResponse",
    "ListPriceListsResponse",
    "ListProductCategoriesResponse",
    "ListProductsResponse",
    "ListProductsResponsePage",
    "ListReceiptsResponse",
    "ListReceiptsResponsePage",
    "ListReceivedDocumentCategoriesResponse",
    "ListReceivedDocumentsResponse",
    "ListReceivedDocumentsResponsePage",
    "ListRevenueCentersResponse",
    "ListSuppliersResponse",
    "ListSuppliersResponsePage",
    "ListTemplatesResponse",
    "ListUnitsOfMeasureResponse",
    "ListUserCompaniesResponse",
    "ListUserCompaniesResponseData",
    "ListVatTypesResponse",
    "ListWebhooksSubscriptionsResponse",
    "ModifyArchiveDocumentRequest",
    "ModifyArchiveDocumentResponse",
    "ModifyCashbookEntryRequest",
    "ModifyCashbookEntryResponse",
    "ModifyClientRequest",
    "ModifyClientResponse",
    "ModifyF24Request",
    "ModifyF24Response",
    "ModifyIssuedDocumentRequest",
    "ModifyIssuedDocumentResponse",
    "ModifyPaymentAccountRequest",
    "ModifyPaymentAccountResponse",
    "ModifyPaymentMethodRequest",
    "ModifyPaymentMethodResponse",
    "ModifyProductRequest",
    "ModifyProductResponse",
    "ModifyReceiptRequest",
    "ModifyReceiptResponse",
    "ModifyReceivedDocumentRequest",
    "ModifyReceivedDocumentResponse",
    "ModifySupplierRequest",
    "ModifySupplierResponse",
    "ModifyVatTypeRequest",
    "ModifyVatTypeResponse",
    "ModifyWebhooksSubscriptionRequest",
    "ModifyWebhooksSubscriptionResponse",
    "MonthlyTotal",
    "OriginalDocumentType",
    "Pagination",
    "PaymentAccount",
    "PaymentAccountType",
    "PaymentMethod",
    "PaymentMethodDetails",
    "PaymentMethodType",
    "PaymentTermsType",
    "PermissionLevel",
    "Permissions",
    "PermissionsFicIssuedDocumentsDetailed",
    "PriceList",
    "PriceListItem",
    "PriceListPricesType",
    "PriceListType",
    "Product",
    "Receipt",
    "ReceiptItemsListItem",
    "ReceiptPreCreateInfo",
    "ReceiptType",
    "ReceivedDocument",
    "ReceivedDocumentInfo",
    "ReceivedDocumentInfoDefaultValues",
    "ReceivedDocumentInfoItemsDefaultValues",
    "ReceivedDocumentItemsListItem",
    "ReceivedDocumentPaymentsListItem",
    "ReceivedDocumentPaymentsListItemPaymentTerms",
    "ReceivedDocumentTotals",
    "ReceivedDocumentType",
    "ScheduleEmailRequest",
    "SendEInvoiceRequest",
    "SendEInvoiceRequestData",
    "SendEInvoiceRequestOptions",
    "SendEInvoiceResponse",
    "SendEInvoiceResponseData",
    "SenderEmail",
    "ShowTotalsMode",
    "Supplier",
    "SupplierType",
    "TaxProfile",
    "TransformIssuedDocumentResponse",
    "UploadArchiveAttachmentResponse",
    "UploadF24AttachmentResponse",
    "UploadIssuedDocumentAttachmentResponse",
    "UploadReceivedDocumentAttachmentResponse",
    "User",
    "UserCompanyRole",
    "VatItem",
    "VatKind",
    "VatType",
    "VerifyEInvoiceXmlErrorResponse",
    "VerifyEInvoiceXmlErrorResponseError",
    "VerifyEInvoiceXmlErrorResponseErrorValidationResult",
    "VerifyEInvoiceXmlErrorResponseExtra",
    "VerifyEInvoiceXmlResponse",
    "VerifyEInvoiceXmlResponseData",
    "VerifyWebhooksSubscription",
    "VerifyWebhooksSubscriptionRequest",
    "WebhooksSubscription",
    "WebhooksSubscriptionConfig",
    "WebhooksSubscriptionMapping",
    "WebhooksSubscriptionVerificationMethod",
]

# import apis into sdk package
from fattureincloud_python_sdk.api.archive_api import ArchiveApi as ArchiveApi
from fattureincloud_python_sdk.api.cashbook_api import CashbookApi as CashbookApi
from fattureincloud_python_sdk.api.clients_api import ClientsApi as ClientsApi
from fattureincloud_python_sdk.api.companies_api import CompaniesApi as CompaniesApi
from fattureincloud_python_sdk.api.emails_api import EmailsApi as EmailsApi
from fattureincloud_python_sdk.api.info_api import InfoApi as InfoApi
from fattureincloud_python_sdk.api.issued_documents_api import IssuedDocumentsApi as IssuedDocumentsApi
from fattureincloud_python_sdk.api.issued_e_invoices_api import IssuedEInvoicesApi as IssuedEInvoicesApi
from fattureincloud_python_sdk.api.price_lists_api import PriceListsApi as PriceListsApi
from fattureincloud_python_sdk.api.products_api import ProductsApi as ProductsApi
from fattureincloud_python_sdk.api.receipts_api import ReceiptsApi as ReceiptsApi
from fattureincloud_python_sdk.api.received_documents_api import ReceivedDocumentsApi as ReceivedDocumentsApi
from fattureincloud_python_sdk.api.settings_api import SettingsApi as SettingsApi
from fattureincloud_python_sdk.api.suppliers_api import SuppliersApi as SuppliersApi
from fattureincloud_python_sdk.api.taxes_api import TaxesApi as TaxesApi
from fattureincloud_python_sdk.api.user_api import UserApi as UserApi
from fattureincloud_python_sdk.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from fattureincloud_python_sdk.api_response import ApiResponse as ApiResponse
from fattureincloud_python_sdk.api_client import ApiClient as ApiClient
from fattureincloud_python_sdk.configuration import Configuration as Configuration
from fattureincloud_python_sdk.exceptions import OpenApiException as OpenApiException
from fattureincloud_python_sdk.exceptions import ApiTypeError as ApiTypeError
from fattureincloud_python_sdk.exceptions import ApiValueError as ApiValueError
from fattureincloud_python_sdk.exceptions import ApiKeyError as ApiKeyError
from fattureincloud_python_sdk.exceptions import ApiAttributeError as ApiAttributeError
from fattureincloud_python_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from fattureincloud_python_sdk.models.archive_document import ArchiveDocument as ArchiveDocument
from fattureincloud_python_sdk.models.attachment_data import AttachmentData as AttachmentData
from fattureincloud_python_sdk.models.cashbook_entry import CashbookEntry as CashbookEntry
from fattureincloud_python_sdk.models.cashbook_entry_document import CashbookEntryDocument as CashbookEntryDocument
from fattureincloud_python_sdk.models.cashbook_entry_kind import CashbookEntryKind as CashbookEntryKind
from fattureincloud_python_sdk.models.cashbook_entry_type import CashbookEntryType as CashbookEntryType
from fattureincloud_python_sdk.models.city import City as City
from fattureincloud_python_sdk.models.client import Client as Client
from fattureincloud_python_sdk.models.client_type import ClientType as ClientType
from fattureincloud_python_sdk.models.company import Company as Company
from fattureincloud_python_sdk.models.company_info import CompanyInfo as CompanyInfo
from fattureincloud_python_sdk.models.company_info_access_info import CompanyInfoAccessInfo as CompanyInfoAccessInfo
from fattureincloud_python_sdk.models.company_info_plan_info import CompanyInfoPlanInfo as CompanyInfoPlanInfo
from fattureincloud_python_sdk.models.company_info_plan_info_functions import CompanyInfoPlanInfoFunctions as CompanyInfoPlanInfoFunctions
from fattureincloud_python_sdk.models.company_info_plan_info_functions_status import CompanyInfoPlanInfoFunctionsStatus as CompanyInfoPlanInfoFunctionsStatus
from fattureincloud_python_sdk.models.company_info_plan_info_limits import CompanyInfoPlanInfoLimits as CompanyInfoPlanInfoLimits
from fattureincloud_python_sdk.models.company_plan_usage import CompanyPlanUsage as CompanyPlanUsage
from fattureincloud_python_sdk.models.company_type import CompanyType as CompanyType
from fattureincloud_python_sdk.models.controlled_company import ControlledCompany as ControlledCompany
from fattureincloud_python_sdk.models.create_archive_document_request import CreateArchiveDocumentRequest as CreateArchiveDocumentRequest
from fattureincloud_python_sdk.models.create_archive_document_response import CreateArchiveDocumentResponse as CreateArchiveDocumentResponse
from fattureincloud_python_sdk.models.create_cashbook_entry_request import CreateCashbookEntryRequest as CreateCashbookEntryRequest
from fattureincloud_python_sdk.models.create_cashbook_entry_response import CreateCashbookEntryResponse as CreateCashbookEntryResponse
from fattureincloud_python_sdk.models.create_client_request import CreateClientRequest as CreateClientRequest
from fattureincloud_python_sdk.models.create_client_response import CreateClientResponse as CreateClientResponse
from fattureincloud_python_sdk.models.create_f24_request import CreateF24Request as CreateF24Request
from fattureincloud_python_sdk.models.create_f24_response import CreateF24Response as CreateF24Response
from fattureincloud_python_sdk.models.create_issued_document_request import CreateIssuedDocumentRequest as CreateIssuedDocumentRequest
from fattureincloud_python_sdk.models.create_issued_document_response import CreateIssuedDocumentResponse as CreateIssuedDocumentResponse
from fattureincloud_python_sdk.models.create_payment_account_request import CreatePaymentAccountRequest as CreatePaymentAccountRequest
from fattureincloud_python_sdk.models.create_payment_account_response import CreatePaymentAccountResponse as CreatePaymentAccountResponse
from fattureincloud_python_sdk.models.create_payment_method_request import CreatePaymentMethodRequest as CreatePaymentMethodRequest
from fattureincloud_python_sdk.models.create_payment_method_response import CreatePaymentMethodResponse as CreatePaymentMethodResponse
from fattureincloud_python_sdk.models.create_product_request import CreateProductRequest as CreateProductRequest
from fattureincloud_python_sdk.models.create_product_response import CreateProductResponse as CreateProductResponse
from fattureincloud_python_sdk.models.create_receipt_request import CreateReceiptRequest as CreateReceiptRequest
from fattureincloud_python_sdk.models.create_receipt_response import CreateReceiptResponse as CreateReceiptResponse
from fattureincloud_python_sdk.models.create_received_document_request import CreateReceivedDocumentRequest as CreateReceivedDocumentRequest
from fattureincloud_python_sdk.models.create_received_document_response import CreateReceivedDocumentResponse as CreateReceivedDocumentResponse
from fattureincloud_python_sdk.models.create_supplier_request import CreateSupplierRequest as CreateSupplierRequest
from fattureincloud_python_sdk.models.create_supplier_response import CreateSupplierResponse as CreateSupplierResponse
from fattureincloud_python_sdk.models.create_vat_type_request import CreateVatTypeRequest as CreateVatTypeRequest
from fattureincloud_python_sdk.models.create_vat_type_response import CreateVatTypeResponse as CreateVatTypeResponse
from fattureincloud_python_sdk.models.create_webhooks_subscription_request import CreateWebhooksSubscriptionRequest as CreateWebhooksSubscriptionRequest
from fattureincloud_python_sdk.models.create_webhooks_subscription_response import CreateWebhooksSubscriptionResponse as CreateWebhooksSubscriptionResponse
from fattureincloud_python_sdk.models.currency import Currency as Currency
from fattureincloud_python_sdk.models.detailed_country import DetailedCountry as DetailedCountry
from fattureincloud_python_sdk.models.document_template import DocumentTemplate as DocumentTemplate
from fattureincloud_python_sdk.models.e_invoice_rejection_reason import EInvoiceRejectionReason as EInvoiceRejectionReason
from fattureincloud_python_sdk.models.email import Email as Email
from fattureincloud_python_sdk.models.email_attachment import EmailAttachment as EmailAttachment
from fattureincloud_python_sdk.models.email_data import EmailData as EmailData
from fattureincloud_python_sdk.models.email_data_default_sender_email import EmailDataDefaultSenderEmail as EmailDataDefaultSenderEmail
from fattureincloud_python_sdk.models.email_recipient_status import EmailRecipientStatus as EmailRecipientStatus
from fattureincloud_python_sdk.models.email_schedule import EmailSchedule as EmailSchedule
from fattureincloud_python_sdk.models.email_schedule_include import EmailScheduleInclude as EmailScheduleInclude
from fattureincloud_python_sdk.models.email_status import EmailStatus as EmailStatus
from fattureincloud_python_sdk.models.entity import Entity as Entity
from fattureincloud_python_sdk.models.entity_client_pre_create_info import EntityClientPreCreateInfo as EntityClientPreCreateInfo
from fattureincloud_python_sdk.models.entity_type import EntityType as EntityType
from fattureincloud_python_sdk.models.event_type import EventType as EventType
from fattureincloud_python_sdk.models.f24 import F24 as F24
from fattureincloud_python_sdk.models.f24_status import F24Status as F24Status
from fattureincloud_python_sdk.models.fatture_in_cloud_plan_type import FattureInCloudPlanType as FattureInCloudPlanType
from fattureincloud_python_sdk.models.function_status import FunctionStatus as FunctionStatus
from fattureincloud_python_sdk.models.get_archive_document_response import GetArchiveDocumentResponse as GetArchiveDocumentResponse
from fattureincloud_python_sdk.models.get_bin_issued_document_response import GetBinIssuedDocumentResponse as GetBinIssuedDocumentResponse
from fattureincloud_python_sdk.models.get_bin_received_document_response import GetBinReceivedDocumentResponse as GetBinReceivedDocumentResponse
from fattureincloud_python_sdk.models.get_cashbook_entry_response import GetCashbookEntryResponse as GetCashbookEntryResponse
from fattureincloud_python_sdk.models.get_client_response import GetClientResponse as GetClientResponse
from fattureincloud_python_sdk.models.get_company_info_response import GetCompanyInfoResponse as GetCompanyInfoResponse
from fattureincloud_python_sdk.models.get_company_plan_usage_response import GetCompanyPlanUsageResponse as GetCompanyPlanUsageResponse
from fattureincloud_python_sdk.models.get_e_invoice_rejection_reason_response import GetEInvoiceRejectionReasonResponse as GetEInvoiceRejectionReasonResponse
from fattureincloud_python_sdk.models.get_email_data_response import GetEmailDataResponse as GetEmailDataResponse
from fattureincloud_python_sdk.models.get_entity_client_pre_create_info_response import GetEntityClientPreCreateInfoResponse as GetEntityClientPreCreateInfoResponse
from fattureincloud_python_sdk.models.get_existing_issued_document_totals_request import GetExistingIssuedDocumentTotalsRequest as GetExistingIssuedDocumentTotalsRequest
from fattureincloud_python_sdk.models.get_existing_issued_document_totals_response import GetExistingIssuedDocumentTotalsResponse as GetExistingIssuedDocumentTotalsResponse
from fattureincloud_python_sdk.models.get_existing_received_document_totals_request import GetExistingReceivedDocumentTotalsRequest as GetExistingReceivedDocumentTotalsRequest
from fattureincloud_python_sdk.models.get_existing_received_document_totals_response import GetExistingReceivedDocumentTotalsResponse as GetExistingReceivedDocumentTotalsResponse
from fattureincloud_python_sdk.models.get_f24_response import GetF24Response as GetF24Response
from fattureincloud_python_sdk.models.get_issued_document_pre_create_info_response import GetIssuedDocumentPreCreateInfoResponse as GetIssuedDocumentPreCreateInfoResponse
from fattureincloud_python_sdk.models.get_issued_document_response import GetIssuedDocumentResponse as GetIssuedDocumentResponse
from fattureincloud_python_sdk.models.get_new_issued_document_totals_request import GetNewIssuedDocumentTotalsRequest as GetNewIssuedDocumentTotalsRequest
from fattureincloud_python_sdk.models.get_new_issued_document_totals_response import GetNewIssuedDocumentTotalsResponse as GetNewIssuedDocumentTotalsResponse
from fattureincloud_python_sdk.models.get_new_received_document_totals_request import GetNewReceivedDocumentTotalsRequest as GetNewReceivedDocumentTotalsRequest
from fattureincloud_python_sdk.models.get_new_received_document_totals_response import GetNewReceivedDocumentTotalsResponse as GetNewReceivedDocumentTotalsResponse
from fattureincloud_python_sdk.models.get_payment_account_response import GetPaymentAccountResponse as GetPaymentAccountResponse
from fattureincloud_python_sdk.models.get_payment_method_response import GetPaymentMethodResponse as GetPaymentMethodResponse
from fattureincloud_python_sdk.models.get_price_list_items_response import GetPriceListItemsResponse as GetPriceListItemsResponse
from fattureincloud_python_sdk.models.get_product_response import GetProductResponse as GetProductResponse
from fattureincloud_python_sdk.models.get_receipt_pre_create_info_response import GetReceiptPreCreateInfoResponse as GetReceiptPreCreateInfoResponse
from fattureincloud_python_sdk.models.get_receipt_response import GetReceiptResponse as GetReceiptResponse
from fattureincloud_python_sdk.models.get_receipts_monthly_totals_response import GetReceiptsMonthlyTotalsResponse as GetReceiptsMonthlyTotalsResponse
from fattureincloud_python_sdk.models.get_received_document_pre_create_info_response import GetReceivedDocumentPreCreateInfoResponse as GetReceivedDocumentPreCreateInfoResponse
from fattureincloud_python_sdk.models.get_received_document_response import GetReceivedDocumentResponse as GetReceivedDocumentResponse
from fattureincloud_python_sdk.models.get_supplier_response import GetSupplierResponse as GetSupplierResponse
from fattureincloud_python_sdk.models.get_tax_profile_response import GetTaxProfileResponse as GetTaxProfileResponse
from fattureincloud_python_sdk.models.get_user_info_response import GetUserInfoResponse as GetUserInfoResponse
from fattureincloud_python_sdk.models.get_user_info_response_email_confirmation_state import GetUserInfoResponseEmailConfirmationState as GetUserInfoResponseEmailConfirmationState
from fattureincloud_python_sdk.models.get_user_info_response_info import GetUserInfoResponseInfo as GetUserInfoResponseInfo
from fattureincloud_python_sdk.models.get_vat_type_response import GetVatTypeResponse as GetVatTypeResponse
from fattureincloud_python_sdk.models.get_webhooks_subscription_response import GetWebhooksSubscriptionResponse as GetWebhooksSubscriptionResponse
from fattureincloud_python_sdk.models.issued_document import IssuedDocument as IssuedDocument
from fattureincloud_python_sdk.models.issued_document_ei_data import IssuedDocumentEiData as IssuedDocumentEiData
from fattureincloud_python_sdk.models.issued_document_extra_data import IssuedDocumentExtraData as IssuedDocumentExtraData
from fattureincloud_python_sdk.models.issued_document_items_list_item import IssuedDocumentItemsListItem as IssuedDocumentItemsListItem
from fattureincloud_python_sdk.models.issued_document_options import IssuedDocumentOptions as IssuedDocumentOptions
from fattureincloud_python_sdk.models.issued_document_payments_list_item import IssuedDocumentPaymentsListItem as IssuedDocumentPaymentsListItem
from fattureincloud_python_sdk.models.issued_document_payments_list_item_payment_terms import IssuedDocumentPaymentsListItemPaymentTerms as IssuedDocumentPaymentsListItemPaymentTerms
from fattureincloud_python_sdk.models.issued_document_pre_create_info import IssuedDocumentPreCreateInfo as IssuedDocumentPreCreateInfo
from fattureincloud_python_sdk.models.issued_document_pre_create_info_default_values import IssuedDocumentPreCreateInfoDefaultValues as IssuedDocumentPreCreateInfoDefaultValues
from fattureincloud_python_sdk.models.issued_document_pre_create_info_extra_data_default_values import IssuedDocumentPreCreateInfoExtraDataDefaultValues as IssuedDocumentPreCreateInfoExtraDataDefaultValues
from fattureincloud_python_sdk.models.issued_document_pre_create_info_items_default_values import IssuedDocumentPreCreateInfoItemsDefaultValues as IssuedDocumentPreCreateInfoItemsDefaultValues
from fattureincloud_python_sdk.models.issued_document_status import IssuedDocumentStatus as IssuedDocumentStatus
from fattureincloud_python_sdk.models.issued_document_totals import IssuedDocumentTotals as IssuedDocumentTotals
from fattureincloud_python_sdk.models.issued_document_type import IssuedDocumentType as IssuedDocumentType
from fattureincloud_python_sdk.models.join_issued_documents_response import JoinIssuedDocumentsResponse as JoinIssuedDocumentsResponse
from fattureincloud_python_sdk.models.language import Language as Language
from fattureincloud_python_sdk.models.list_archive_categories_response import ListArchiveCategoriesResponse as ListArchiveCategoriesResponse
from fattureincloud_python_sdk.models.list_archive_documents_response import ListArchiveDocumentsResponse as ListArchiveDocumentsResponse
from fattureincloud_python_sdk.models.list_archive_documents_response_page import ListArchiveDocumentsResponsePage as ListArchiveDocumentsResponsePage
from fattureincloud_python_sdk.models.list_bin_issued_documents import ListBinIssuedDocuments as ListBinIssuedDocuments
from fattureincloud_python_sdk.models.list_bin_received_documents import ListBinReceivedDocuments as ListBinReceivedDocuments
from fattureincloud_python_sdk.models.list_cashbook_entries_response import ListCashbookEntriesResponse as ListCashbookEntriesResponse
from fattureincloud_python_sdk.models.list_cities_response import ListCitiesResponse as ListCitiesResponse
from fattureincloud_python_sdk.models.list_clients_response import ListClientsResponse as ListClientsResponse
from fattureincloud_python_sdk.models.list_clients_response_page import ListClientsResponsePage as ListClientsResponsePage
from fattureincloud_python_sdk.models.list_cost_centers_response import ListCostCentersResponse as ListCostCentersResponse
from fattureincloud_python_sdk.models.list_countries_response import ListCountriesResponse as ListCountriesResponse
from fattureincloud_python_sdk.models.list_currencies_response import ListCurrenciesResponse as ListCurrenciesResponse
from fattureincloud_python_sdk.models.list_delivery_notes_default_causals_response import ListDeliveryNotesDefaultCausalsResponse as ListDeliveryNotesDefaultCausalsResponse
from fattureincloud_python_sdk.models.list_detailed_countries_response import ListDetailedCountriesResponse as ListDetailedCountriesResponse
from fattureincloud_python_sdk.models.list_emails_response import ListEmailsResponse as ListEmailsResponse
from fattureincloud_python_sdk.models.list_emails_response_page import ListEmailsResponsePage as ListEmailsResponsePage
from fattureincloud_python_sdk.models.list_f24_response import ListF24Response as ListF24Response
from fattureincloud_python_sdk.models.list_f24_response_aggregated_data import ListF24ResponseAggregatedData as ListF24ResponseAggregatedData
from fattureincloud_python_sdk.models.list_f24_response_aggregation import ListF24ResponseAggregation as ListF24ResponseAggregation
from fattureincloud_python_sdk.models.list_f24_response_page import ListF24ResponsePage as ListF24ResponsePage
from fattureincloud_python_sdk.models.list_issued_documents_response import ListIssuedDocumentsResponse as ListIssuedDocumentsResponse
from fattureincloud_python_sdk.models.list_issued_documents_response_page import ListIssuedDocumentsResponsePage as ListIssuedDocumentsResponsePage
from fattureincloud_python_sdk.models.list_languages_response import ListLanguagesResponse as ListLanguagesResponse
from fattureincloud_python_sdk.models.list_payment_accounts_response import ListPaymentAccountsResponse as ListPaymentAccountsResponse
from fattureincloud_python_sdk.models.list_payment_methods_response import ListPaymentMethodsResponse as ListPaymentMethodsResponse
from fattureincloud_python_sdk.models.list_price_lists_response import ListPriceListsResponse as ListPriceListsResponse
from fattureincloud_python_sdk.models.list_product_categories_response import ListProductCategoriesResponse as ListProductCategoriesResponse
from fattureincloud_python_sdk.models.list_products_response import ListProductsResponse as ListProductsResponse
from fattureincloud_python_sdk.models.list_products_response_page import ListProductsResponsePage as ListProductsResponsePage
from fattureincloud_python_sdk.models.list_receipts_response import ListReceiptsResponse as ListReceiptsResponse
from fattureincloud_python_sdk.models.list_receipts_response_page import ListReceiptsResponsePage as ListReceiptsResponsePage
from fattureincloud_python_sdk.models.list_received_document_categories_response import ListReceivedDocumentCategoriesResponse as ListReceivedDocumentCategoriesResponse
from fattureincloud_python_sdk.models.list_received_documents_response import ListReceivedDocumentsResponse as ListReceivedDocumentsResponse
from fattureincloud_python_sdk.models.list_received_documents_response_page import ListReceivedDocumentsResponsePage as ListReceivedDocumentsResponsePage
from fattureincloud_python_sdk.models.list_revenue_centers_response import ListRevenueCentersResponse as ListRevenueCentersResponse
from fattureincloud_python_sdk.models.list_suppliers_response import ListSuppliersResponse as ListSuppliersResponse
from fattureincloud_python_sdk.models.list_suppliers_response_page import ListSuppliersResponsePage as ListSuppliersResponsePage
from fattureincloud_python_sdk.models.list_templates_response import ListTemplatesResponse as ListTemplatesResponse
from fattureincloud_python_sdk.models.list_units_of_measure_response import ListUnitsOfMeasureResponse as ListUnitsOfMeasureResponse
from fattureincloud_python_sdk.models.list_user_companies_response import ListUserCompaniesResponse as ListUserCompaniesResponse
from fattureincloud_python_sdk.models.list_user_companies_response_data import ListUserCompaniesResponseData as ListUserCompaniesResponseData
from fattureincloud_python_sdk.models.list_vat_types_response import ListVatTypesResponse as ListVatTypesResponse
from fattureincloud_python_sdk.models.list_webhooks_subscriptions_response import ListWebhooksSubscriptionsResponse as ListWebhooksSubscriptionsResponse
from fattureincloud_python_sdk.models.modify_archive_document_request import ModifyArchiveDocumentRequest as ModifyArchiveDocumentRequest
from fattureincloud_python_sdk.models.modify_archive_document_response import ModifyArchiveDocumentResponse as ModifyArchiveDocumentResponse
from fattureincloud_python_sdk.models.modify_cashbook_entry_request import ModifyCashbookEntryRequest as ModifyCashbookEntryRequest
from fattureincloud_python_sdk.models.modify_cashbook_entry_response import ModifyCashbookEntryResponse as ModifyCashbookEntryResponse
from fattureincloud_python_sdk.models.modify_client_request import ModifyClientRequest as ModifyClientRequest
from fattureincloud_python_sdk.models.modify_client_response import ModifyClientResponse as ModifyClientResponse
from fattureincloud_python_sdk.models.modify_f24_request import ModifyF24Request as ModifyF24Request
from fattureincloud_python_sdk.models.modify_f24_response import ModifyF24Response as ModifyF24Response
from fattureincloud_python_sdk.models.modify_issued_document_request import ModifyIssuedDocumentRequest as ModifyIssuedDocumentRequest
from fattureincloud_python_sdk.models.modify_issued_document_response import ModifyIssuedDocumentResponse as ModifyIssuedDocumentResponse
from fattureincloud_python_sdk.models.modify_payment_account_request import ModifyPaymentAccountRequest as ModifyPaymentAccountRequest
from fattureincloud_python_sdk.models.modify_payment_account_response import ModifyPaymentAccountResponse as ModifyPaymentAccountResponse
from fattureincloud_python_sdk.models.modify_payment_method_request import ModifyPaymentMethodRequest as ModifyPaymentMethodRequest
from fattureincloud_python_sdk.models.modify_payment_method_response import ModifyPaymentMethodResponse as ModifyPaymentMethodResponse
from fattureincloud_python_sdk.models.modify_product_request import ModifyProductRequest as ModifyProductRequest
from fattureincloud_python_sdk.models.modify_product_response import ModifyProductResponse as ModifyProductResponse
from fattureincloud_python_sdk.models.modify_receipt_request import ModifyReceiptRequest as ModifyReceiptRequest
from fattureincloud_python_sdk.models.modify_receipt_response import ModifyReceiptResponse as ModifyReceiptResponse
from fattureincloud_python_sdk.models.modify_received_document_request import ModifyReceivedDocumentRequest as ModifyReceivedDocumentRequest
from fattureincloud_python_sdk.models.modify_received_document_response import ModifyReceivedDocumentResponse as ModifyReceivedDocumentResponse
from fattureincloud_python_sdk.models.modify_supplier_request import ModifySupplierRequest as ModifySupplierRequest
from fattureincloud_python_sdk.models.modify_supplier_response import ModifySupplierResponse as ModifySupplierResponse
from fattureincloud_python_sdk.models.modify_vat_type_request import ModifyVatTypeRequest as ModifyVatTypeRequest
from fattureincloud_python_sdk.models.modify_vat_type_response import ModifyVatTypeResponse as ModifyVatTypeResponse
from fattureincloud_python_sdk.models.modify_webhooks_subscription_request import ModifyWebhooksSubscriptionRequest as ModifyWebhooksSubscriptionRequest
from fattureincloud_python_sdk.models.modify_webhooks_subscription_response import ModifyWebhooksSubscriptionResponse as ModifyWebhooksSubscriptionResponse
from fattureincloud_python_sdk.models.monthly_total import MonthlyTotal as MonthlyTotal
from fattureincloud_python_sdk.models.original_document_type import OriginalDocumentType as OriginalDocumentType
from fattureincloud_python_sdk.models.pagination import Pagination as Pagination
from fattureincloud_python_sdk.models.payment_account import PaymentAccount as PaymentAccount
from fattureincloud_python_sdk.models.payment_account_type import PaymentAccountType as PaymentAccountType
from fattureincloud_python_sdk.models.payment_method import PaymentMethod as PaymentMethod
from fattureincloud_python_sdk.models.payment_method_details import PaymentMethodDetails as PaymentMethodDetails
from fattureincloud_python_sdk.models.payment_method_type import PaymentMethodType as PaymentMethodType
from fattureincloud_python_sdk.models.payment_terms_type import PaymentTermsType as PaymentTermsType
from fattureincloud_python_sdk.models.permission_level import PermissionLevel as PermissionLevel
from fattureincloud_python_sdk.models.permissions import Permissions as Permissions
from fattureincloud_python_sdk.models.permissions_fic_issued_documents_detailed import PermissionsFicIssuedDocumentsDetailed as PermissionsFicIssuedDocumentsDetailed
from fattureincloud_python_sdk.models.price_list import PriceList as PriceList
from fattureincloud_python_sdk.models.price_list_item import PriceListItem as PriceListItem
from fattureincloud_python_sdk.models.price_list_prices_type import PriceListPricesType as PriceListPricesType
from fattureincloud_python_sdk.models.price_list_type import PriceListType as PriceListType
from fattureincloud_python_sdk.models.product import Product as Product
from fattureincloud_python_sdk.models.receipt import Receipt as Receipt
from fattureincloud_python_sdk.models.receipt_items_list_item import ReceiptItemsListItem as ReceiptItemsListItem
from fattureincloud_python_sdk.models.receipt_pre_create_info import ReceiptPreCreateInfo as ReceiptPreCreateInfo
from fattureincloud_python_sdk.models.receipt_type import ReceiptType as ReceiptType
from fattureincloud_python_sdk.models.received_document import ReceivedDocument as ReceivedDocument
from fattureincloud_python_sdk.models.received_document_info import ReceivedDocumentInfo as ReceivedDocumentInfo
from fattureincloud_python_sdk.models.received_document_info_default_values import ReceivedDocumentInfoDefaultValues as ReceivedDocumentInfoDefaultValues
from fattureincloud_python_sdk.models.received_document_info_items_default_values import ReceivedDocumentInfoItemsDefaultValues as ReceivedDocumentInfoItemsDefaultValues
from fattureincloud_python_sdk.models.received_document_items_list_item import ReceivedDocumentItemsListItem as ReceivedDocumentItemsListItem
from fattureincloud_python_sdk.models.received_document_payments_list_item import ReceivedDocumentPaymentsListItem as ReceivedDocumentPaymentsListItem
from fattureincloud_python_sdk.models.received_document_payments_list_item_payment_terms import ReceivedDocumentPaymentsListItemPaymentTerms as ReceivedDocumentPaymentsListItemPaymentTerms
from fattureincloud_python_sdk.models.received_document_totals import ReceivedDocumentTotals as ReceivedDocumentTotals
from fattureincloud_python_sdk.models.received_document_type import ReceivedDocumentType as ReceivedDocumentType
from fattureincloud_python_sdk.models.schedule_email_request import ScheduleEmailRequest as ScheduleEmailRequest
from fattureincloud_python_sdk.models.send_e_invoice_request import SendEInvoiceRequest as SendEInvoiceRequest
from fattureincloud_python_sdk.models.send_e_invoice_request_data import SendEInvoiceRequestData as SendEInvoiceRequestData
from fattureincloud_python_sdk.models.send_e_invoice_request_options import SendEInvoiceRequestOptions as SendEInvoiceRequestOptions
from fattureincloud_python_sdk.models.send_e_invoice_response import SendEInvoiceResponse as SendEInvoiceResponse
from fattureincloud_python_sdk.models.send_e_invoice_response_data import SendEInvoiceResponseData as SendEInvoiceResponseData
from fattureincloud_python_sdk.models.sender_email import SenderEmail as SenderEmail
from fattureincloud_python_sdk.models.show_totals_mode import ShowTotalsMode as ShowTotalsMode
from fattureincloud_python_sdk.models.supplier import Supplier as Supplier
from fattureincloud_python_sdk.models.supplier_type import SupplierType as SupplierType
from fattureincloud_python_sdk.models.tax_profile import TaxProfile as TaxProfile
from fattureincloud_python_sdk.models.transform_issued_document_response import TransformIssuedDocumentResponse as TransformIssuedDocumentResponse
from fattureincloud_python_sdk.models.upload_archive_attachment_response import UploadArchiveAttachmentResponse as UploadArchiveAttachmentResponse
from fattureincloud_python_sdk.models.upload_f24_attachment_response import UploadF24AttachmentResponse as UploadF24AttachmentResponse
from fattureincloud_python_sdk.models.upload_issued_document_attachment_response import UploadIssuedDocumentAttachmentResponse as UploadIssuedDocumentAttachmentResponse
from fattureincloud_python_sdk.models.upload_received_document_attachment_response import UploadReceivedDocumentAttachmentResponse as UploadReceivedDocumentAttachmentResponse
from fattureincloud_python_sdk.models.user import User as User
from fattureincloud_python_sdk.models.user_company_role import UserCompanyRole as UserCompanyRole
from fattureincloud_python_sdk.models.vat_item import VatItem as VatItem
from fattureincloud_python_sdk.models.vat_kind import VatKind as VatKind
from fattureincloud_python_sdk.models.vat_type import VatType as VatType
from fattureincloud_python_sdk.models.verify_e_invoice_xml_error_response import VerifyEInvoiceXmlErrorResponse as VerifyEInvoiceXmlErrorResponse
from fattureincloud_python_sdk.models.verify_e_invoice_xml_error_response_error import VerifyEInvoiceXmlErrorResponseError as VerifyEInvoiceXmlErrorResponseError
from fattureincloud_python_sdk.models.verify_e_invoice_xml_error_response_error_validation_result import VerifyEInvoiceXmlErrorResponseErrorValidationResult as VerifyEInvoiceXmlErrorResponseErrorValidationResult
from fattureincloud_python_sdk.models.verify_e_invoice_xml_error_response_extra import VerifyEInvoiceXmlErrorResponseExtra as VerifyEInvoiceXmlErrorResponseExtra
from fattureincloud_python_sdk.models.verify_e_invoice_xml_response import VerifyEInvoiceXmlResponse as VerifyEInvoiceXmlResponse
from fattureincloud_python_sdk.models.verify_e_invoice_xml_response_data import VerifyEInvoiceXmlResponseData as VerifyEInvoiceXmlResponseData
from fattureincloud_python_sdk.models.verify_webhooks_subscription import VerifyWebhooksSubscription as VerifyWebhooksSubscription
from fattureincloud_python_sdk.models.verify_webhooks_subscription_request import VerifyWebhooksSubscriptionRequest as VerifyWebhooksSubscriptionRequest
from fattureincloud_python_sdk.models.webhooks_subscription import WebhooksSubscription as WebhooksSubscription
from fattureincloud_python_sdk.models.webhooks_subscription_config import WebhooksSubscriptionConfig as WebhooksSubscriptionConfig
from fattureincloud_python_sdk.models.webhooks_subscription_mapping import WebhooksSubscriptionMapping as WebhooksSubscriptionMapping
from fattureincloud_python_sdk.models.webhooks_subscription_verification_method import WebhooksSubscriptionVerificationMethod as WebhooksSubscriptionVerificationMethod

